### ISSUE TITLE
Multi Region Support

### ISSUE THREAD

**Issue by jakehow** [ankane/kms_encrypted#13]
Hi, thanks for the project.

In general it is good practice to re-encrypt data keys with another key in an alternate region for disaster recovery and/or failover purposes.

From: https://docs.aws.amazon.com/encryption-sdk/latest/developer-guide/faq.html 

> **Can I encrypt data under more than one master key?**
> Yes. You can encrypt the data key with additional master keys to add redundancy in case a master key is in a different region or is unavailable for decryption.
> 
> To encrypt data under multiple master keys, create a master key provider with multiple master keys. You can see examples of this pattern in the example code for Java and Python.
> 
> When you encrypt data by using a master key provider that returns multiple master keys, the AWS Encryption SDK encrypts the data that you pass to the encryption methods with a data key and encrypts that data key with the same master key. Then, it encrypts the data with the other master keys that the master key provider returned. The resulting message includes the encrypted data and one encrypted data key for each master key. The resulting message can be decrypted by using any one of the master keys used in the encryption operation.

Do you currently have a strategy to do that with this project and attr_encrypted?  Seems like it might require a more complex data storage format for the multiple data keys on the record.

**Comment by ankane** [comment]
Hey @jakehow, thanks for the suggestion. I think this is outside the scope of what I'd like to support (due to added complexity), but you can probably fork the gem to achieve this. The simplest approach I can think of would be:

1. Have the encrypt code encrypt multiple times in different regions
2. Store the encrypted values in the `encrypted_kms_key` field, separated by a delimiter like `:`
3. When `kms_key` is called (where decryption happens), split the encrypted keys and try to decrypt one by one until a call to AWS is successful

If you end up implementing something like this, would love to take a look.

**Comment by jakehow** [comment]
@ankane yeah that makes sense and was sort of what I was thinking.  Will take a hack at it and let you know results.  Closing for now.
